### ISSUE TITLE
The CTC plugins (mastodon-ctc-0.1.2) are incompatible with Mastodon v1.0.0-beta-28

### ISSUE THREAD

**Issue by aherbert** [mastodon-sc/mastodon-ctc#8]
As of 5-Feb-2024 the CTC plugins and Mastodon plugins distributed through the Fiji updater are incompatible.

When starting Mastodon v1.0.0-beta-28 the following stack trace is generated:
```
[WARNING] 2 exceptions occurred during plugin discovery.
Exception in thread "Thread-8" java.lang.NoClassDefFoundError: org/mastodon/mamut/plugin/MamutPluginAppModel
	at org.mastodon.ctc.CTC_Plugins.setAppPluginModel(CTC_Plugins.java:56)
	at org.mastodon.mamut.ProjectModel.lambda$discoverPlugins$1(ProjectModel.java:208)
	at org.mastodon.app.plugin.PluginUtils.lambda$forEachDiscoveredPlugin$0(PluginUtils.java:63)
	at org.mastodon.app.plugin.PluginUtils.forEachDiscoveredPlugin(PluginUtils.java:96)
	at org.mastodon.app.plugin.PluginUtils.forEachDiscoveredPlugin(PluginUtils.java:64)
	at org.mastodon.mamut.ProjectModel.discoverPlugins(ProjectModel.java:211)
	at org.mastodon.mamut.ProjectModel.<init>(ProjectModel.java:132)
	at org.mastodon.mamut.ProjectModel.create(ProjectModel.java:250)
	at org.mastodon.mamut.io.ProjectLoader.open(ProjectLoader.java:193)
	at org.mastodon.mamut.launcher.LauncherUtil.openWithDialog(LauncherUtil.java:332)
	at org.mastodon.mamut.launcher.MastodonLauncher.lambda$loadMastodonProject$19(MastodonLauncher.java:556)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: org.mastodon.mamut.plugin.MamutPluginAppModel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 12 more
```

Disabling the CTC update site allows Mastodon to function as expected. With the CTC plugins installed it cannot open any new or existing Mastodon project. 

CTC update site provides:
```
mastodon-ctc-0.1.2.jar
```

Mastodon update site provides:
```
mastodon-1.0.0-beta-28.jar
```

I presume this is due to a binary incompatible API change in Mastodon. Hopefully the fix is a simple recompile with a compatible CTC change and redistribute.

Note: This may require a downstream change to the plugin discovery mechanism in Mastodon to catch errors, log them, but continue without the incompatible plugins. Currently Mastodon does not gracefully handle incompatible plugins.

Let me know if I should cascade this issue to Mastodon.

**Comment by xulman** [comment]
Thank You very much @aherbert for the report.

Indeed, the new Mastodon plugin API rendered this suite of plugins non-functional with M-beta-28. I'm aware of that and going to fix it right now, finally (also noticed PR from you, very much appreciated!). I'm just lacking behind with necessary fixes here and there, also in other Mastodon plugins of mine :(


-------------
PS: You're right, maybe we should aim at detecting broken plugins on the Mastodon side.. although, I'm not sure how that should be achieved. Do you happen to have an idea?

**Comment by xulman** [comment]
Thank you again for the hints. As I'm currently still following progress and changes in the Mastodon API, I'm *only* not managing to keep the code base up to the tempo. So, I took a note of this (see #11 ).

**Comment by xulman** [comment]
The corresponding PR has been merged. Case closed. Thank you again Alex.

PS: I've [listed you among the code contributors](https://github.com/mastodon-sc/mastodon-ctc/commit/c0c0c7b4fe90800cde4f41682a4a93e75731404e), hope you don't mind...

**Comment by aherbert** [comment]
I have verified that the new version on the Fiji update site is working.

Thanks for the quick turnaround.
